---
- hosts: all
  become: yes

  tasks:
    - name: Create User
      user:
        name: "{{ username }}"
        uid: "{{ uid }}"
        comment: "{{ comment }}"
        password: "{{ password | password_hash('sha512', 'username') }}"
        update_password: on_create

    - name: Force user to change password at next login
      command: passwd --expire {{ username }}