- hosts: all
  tasks:
    - become_user: someuser
      become_method: su
      become_exe: sudo su -
      command: id -u
      register: id_output

    - assert:
        that: id_output.stdout == '0'