- hosts: all
  tasks:
    - become_user: ansible
      remote_user: ansible
      become_method: sudo
      command: id -u
      register: id_output

    - assert:
        that: id_output.stdout == '0'